[project]
name = "autocommit"
version = "0.1.0"
dependencies = ["observer", "pyyaml"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["autocommit"]
