[project]
name = "autocommit"
version = "0.1.0"
dependencies = ["observer", "pyyaml"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"


[tool.setuptools.packages.find]
where = ["."]
